<MyBoxLayout>:
    orientation: 'horizontal'
    BoxLayout:
        size_hint_x: 0.5
        canvas.before:
            Color:
                rgba: 0, 0, 1, 1 # Dark blue color
            Rectangle:
                pos: self.pos
                size: self.size
    BoxLayout:
        size_hint_x: 0.5
        canvas.before:
            Color:
                rgba: 0, 0, 0, 1  # Black color
            Rectangle:
                pos: self.pos
                size: self.size